import os
import platform
import sys
import subprocess

from . import PlatformSDK


from Internal import LinkEnvironment as LE


class ToolchainSDK:

    CppPlatform = ""

    def __init__(self, CppPlat):
        CppPlatform = CppPlat

    # Compile the inputted C++ files into object files
    # <CompileEnv> The Compile Environment
    # <InputFiles> All cpp files to compile
    # <OutDir> The directory of the output
    # <OutputActionList> List of actions that we will generate, will be appended
    # <Return> List of objects files that will be compiled
    def CompileFiles(self, CompileEnv, InputFiles, OutDir, OutputActionList):
        pass  # Will be overwritten with child class

    # FIXME: This isn't complete, as a placeholder just returns CompileCPPs, please replace!
    # CompileCPPs for multi-arch compiles
    # <CompileEnv> The Compile Environment
    # <InputFiles> All cpp files to compile
    # <OutDir> The directory of the output
    # <OutputActionList> List of actions that we will generate, will be appended
    # <Return> List of objects files that will be compiled
    def CompileMultiArchCPPs(self, CompileEnv, InputFiles, OutputDir, OutputActionList):
        return self.CompileFiles(CompileEnv, InputFiles, OutputDir, OutputActionList)

    # Compiles the inputted RCF files
    # <CompileEnv> The compile environment
    # <InputFiles> The input files
    # <OutDir> Output directory
    # <OutputActionList> List of actions that we will generate, will be appended
    def CompileRCFs(CompileEnv, InputFiles, OutDir, OutputActionList):
        pass  # TODO: Make this return new instance of CppOutput

    # Link files in the LinkEnvironment
    # <LinkEnv> The Link Environment
    # <LibraryImportOnly> if true, then we should only compile as a library
    # <OutputActionList> List of actions that we will generate, will be appended
    def LinkFiles(LinkEnv, LibraryImportOnly, OutputActionList):
        pass  # Will be overwritten with child class

    # Link every file in the LinkEnvironment
    # <LinkEnv> The Link Environment
    # <LibraryImportOnly> if true, then we should only compile as a library
    # <ActionList> List of actions that we will generate, will be appended
    def LinkEveryFiles(self, LinkEnv, BuiltLibraryImportOnly, ActionList):
        FileList = []

        FileList.append(self.LinkFiles(LinkEnv, BuiltLibraryImportOnly, ActionList))

        return FileList

    # Return's the actions to do after building and linking
    # <File> The binary file to apply
    # <LinkEnv> The link environment
    # <ActionList> List of actions to generate, will be appended
    # <Return> Output files generated by PostBuilt
    def PostBuilt(self, File, LinkEnv, ActionList):
        Temp = []

        return Temp
